name: Playwright Automation Test Run
on: workflow_dispatch
jobs:
  alltests:
    name: UI Testcases
    runs-on: ubuntu-latest
    #container:
    # image: mcr.microsoft.com/playwright
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Install Browsers for Playwright
        run: npx playwright install
      - name: Installing xvfb
        run: sudo apt-get install xvfb
      - name: Execute Playwright tests
        run:  xvfb-run node producttest.spec.ts
